#!/usr/bin/env bash
# This script displays a list of currently running processes.
# It shows  all processes, for all users, including those which might not have a TTY.
# in a user-oriented format. It shows process hierarchy.

ps -auxf
