#!/usr/bin/env bash
# This script loops from 1 to 10 using a while loop. The 4th iteration displays "bad luck",
# the 8th iteration displays "good luck" and the other iterations display "Best School".

# Initiate the while loop
i=1

while [ $i -le 10 ]
do
	# Introduce the conditions
	if [ $i -eq 4 ]; then
		echo "bad luck"

	elif [ $i -eq 8 ]; then
		echo "good luck"

	else
		echo "Best School"

		
	fi
	(( i++ ))

done
