#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes using a while loop. Hours are displayed from 0 to 12
# and minutes are displayed from 0 to 59.

# The variable h represents hour while m represents minutes.

h=0

while [ $h -le 12 ]
do
       echo "Hour: $h"
       m=1
       while [ $m -le 59 ]
       do
	       echo "$m"
	       (( m++ ))
       done
       (( h++))
done
