#!/usr/bin/env bash
# This script gives information about the "school" file. The script will first check
# if the file exists and then print message according to the file status (empty, not empty, 
# regular or not regular)

FILE=school

# Check if the file exists
if [ -e $FILE ]
then
	echo "school file exists"

	# If the file exists, check if it is empty or not
	if [ -s $FILE ]
	then
		echo "school file is not empty"
	else 
		echo "school file is empty"
	fi

	# If the file exists, check if it is regular or not
	if [ -f $FILE ]
	then
		echo "school is a regular file"
	fi

# Define what happen when the file does not exist	
else
	echo "school file does not exist"
fi
